default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  timeout: 5000
  host: <%=ENV['IP']%>

development:
  <<: *default
  database: microposts_development

test:
  <<: *default
  database: microposts_test

production:
  <<: *default
  database: microposts_production
